export const sneakersBase = [
  {
    name: "Nike",
    img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/05d3daca-d2b5-43de-b651-1aac41fafaf3/air-jordan-1-low-g-golf-shoes-jChrQ3.png",
    price: 100,
    stateBtn: true,
    textBuyBtn: "Добавить в корзину",
    classBuyBtn: "addBtn",
    deleteBtn: false,
    detail: false,
  },
  {
    name: "Reebok",
    img: "https://assets.reebok.com/images/w_600,f_auto,q_auto/833fd67a367243989f55ae4c0017e4eb_9366/Club_C_85_Vintage_Women's_Shoes_White_GX3686_01_standard.jpg",
    price: 300,
    stateBtn: true,
    textBuyBtn: "Добавить в корзину",
    classBuyBtn: "addBtn",
    deleteBtn: false,
    detail: false,
  },
  {
    name: "Adidas",
    img: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/a87c16a30e564404a261acb800d37210_9366/nmd_r1-shoes.jpg",
    price: 500,
    stateBtn: true,
    textBuyBtn: "Добавить в корзину",
    classBuyBtn: "addBtn",
    deleteBtn: false,
    detail: false,
  },
  {
    name: "Puma",
    img: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/376151/04/sv01/fnd/EEA/fmt/png/Fuse-2.0-Men's-Training-Shoes",
    price: 200,
    stateBtn: true,
    textBuyBtn: "Добавить в корзину",
    classBuyBtn: "addBtn",
    deleteBtn: false,
    detail: false,
  },
  {
    name: "Vans",
    img: "https://images.vans.com/is/image/Vans/VN000D3HY28-HERO?hei=1024&wid=1024&qlt=95",
    price: 100,
    stateBtn: true,
    textBuyBtn: "Добавить в корзину",
    classBuyBtn: "addBtn",
    deleteBtn: false,
    detail: false,
  },
  {
    name: "New Balance",
    img: "https://newbalance.ru/upload/resize_cache/iblock/606/992_992_2/ct300wg3_nb_02_i.jpg",
    price: 100,
    stateBtn: true,
    textBuyBtn: "Добавить в корзину",
    classBuyBtn: "addBtn",
    deleteBtn: false,
    detail: false,
  },
];
